In [93]:
!pip install numpy pandas matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.4.3)
Requirement already satisfied: pandas in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.0.1)
Requirement already satisfied: matplotlib in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\jorda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [149]:
import pandas as pd
import numpy as np
import re

In [150]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jorda\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\jorda\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [151]:
data_Train = pd.read_excel("Data_Train.xlsx")
data_Test = pd.read_excel("Test_set.xlsx")
data_prediction_test = pd.read_excel("Sample_submission.xlsx")

In [152]:
data_Train.head(15)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
10,Air India,1/06/2019,Delhi,Cochin,DEL → BLR → COK,09:45,23:00,13h 15m,1 stop,No info,8907
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
12,Air India,24/06/2019,Chennai,Kolkata,MAA → CCU,11:40,13:55,2h 15m,non-stop,No info,4667
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663
14,IndiGo,24/04/2019,Kolkata,Banglore,CCU → BLR,17:15,19:50,2h 35m,non-stop,No info,4804

In [153]:
# infos du dataset d'entrainement 
data_Train.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [154]:
# descriprion ses données d'entrainnement
data_Train.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [155]:
#rechercheons les valeures nulles,
data_Train.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

On remarque que notre data set d'entrainnement possede des valeures manquantes notamment pour les variables Route et Total_Stops

In [156]:
data_Train[data_Train.isnull().any(axis=1)]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [157]:
#drop the nullvalues
data_Train.dropna(inplace=True)

In [158]:
data_Train.dtypes

Airline              str
Date_of_Journey      str
Source               str
Destination          str
Route                str
Dep_Time             str
Arrival_Time         str
Duration             str
Total_Stops          str
Additional_Info      str
Price              int64
dtype: object

On remarque quhe le format des dates n'est pas correct et qu'il faudrait le modifier

In [159]:
def change_into_datetime(col):
    data_Train[col]=pd.to_datetime(data_Train[col])

In [160]:
for i in ['Date_of_Journey','Dep_Time', 'Arrival_Time']:
    change_into_datetime(i)

C:\Users\jorda\AppData\Local\Temp\ipykernel_28140\799145402.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data_Train[col]=pd.to_datetime(data_Train[col])
C:\Users\jorda\AppData\Local\Temp\ipykernel_28140\799145402.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_Train[col]=pd.to_datetime(data_Train[col])
C:\Users\jorda\AppData\Local\Temp\ipykernel_28140\799145402.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_Train[col]=pd.to_datetime(data_Train[col])

In [161]:
data_Train.dtypes

Airline                       str
Date_of_Journey    datetime64[us]
Source                        str
Destination                   str
Route                         str
Dep_Time           datetime64[us]
Arrival_Time       datetime64[us]
Duration                      str
Total_Stops                   str
Additional_Info               str
Price                       int64
dtype: object

In [162]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,2026-03-21 22:20:00,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-03-21 05:50:00,2026-03-21 13:15:00,7h 25m,2 stops,No info,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,2026-03-21 09:25:00,2026-06-10 04:25:00,19h,2 stops,No info,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,2026-03-21 18:05:00,2026-03-21 23:30:00,5h 25m,1 stop,No info,6218
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,2026-03-21 16:50:00,2026-03-21 21:35:00,4h 45m,1 stop,No info,13302

passons à la transformation de la colone Date_of_Journey en 2 colones mois et jour pouvoir faire les differentes analyses temporelles

In [163]:
data_Train["mois_depart"] = data_Train["Date_of_Journey"].dt.month
data_Train["jour_depart"] = data_Train["Date_of_Journey"].dt.day

In [164]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,2026-03-21 22:20:00,2026-03-22 01:10:00,2h 50m,non-stop,No info,3897,3,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,2026-03-21 05:50:00,2026-03-21 13:15:00,7h 25m,2 stops,No info,7662,5,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,2026-03-21 09:25:00,2026-06-10 04:25:00,19h,2 stops,No info,13882,6,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,2026-03-21 18:05:00,2026-03-21 23:30:00,5h 25m,1 stop,No info,6218,5,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,2026-03-21 16:50:00,2026-03-21 21:35:00,4h 45m,1 stop,No info,13302,3,1

In [165]:
data_Train["Dep_Time"] = data_Train["Dep_Time"].dt.strftime("%H:%M")
data_Train["Arrival_Time"] = data_Train["Arrival_Time"].dt.strftime("%H:%M")

In [166]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,3,24
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,5,1
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,6,9
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,5,12
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,3,1

Passons à la gestion de la duree

In [167]:
def convertion_duree(x):
    x = str(x)
    h = 0
    m = 0

    if "h" in x:
        h = int(x.split("h")[0])

    if "m" in x:
        if "h" in x:
            m = int(x.split("h")[1].replace("m", "").strip())
        else:
            m = int(x.replace("m", ""))

    return h*60 + m

data_Train["duree_min"] = data_Train["Duration"].apply(convertion_duree)

In [168]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart,duree_min
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,3,24,170
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,5,1,445
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,6,9,1140
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,5,12,325
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,3,1,285

In [169]:
data_Train["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1751
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [170]:
data_Train["Route"].value_counts()

Route
DEL → BOM → COK                      2376
BLR → DEL                            1552
CCU → BOM → BLR                       979
CCU → BLR                             724
BOM → HYD                             621
                                     ...
BOM → VNS → DEL → HYD                   1
BLR → HBX → BOM → NAG → DEL             1
BLR → BOM → IXC → DEL                   1
BLR → CCU → BBI → HYD → VGA → DEL       1
BOM → BBI → HYD                         1
Name: count, Length: 128, dtype: int64

In [171]:
data_Train.drop("Route", axis=1, inplace=True)

In [172]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart,duree_min
0,IndiGo,2019-03-24,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897,3,24,170
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,5,1,445
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882,6,9,1140
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,5,12,325
4,IndiGo,2019-03-01,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,3,1,285

In [173]:
data_Train.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Date_of_Journey  10682 non-null  datetime64[us]
 2   Source           10682 non-null  str
 3   Destination      10682 non-null  str
 4   Dep_Time         10682 non-null  str
 5   Arrival_Time     10682 non-null  str
 6   Duration         10682 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10682 non-null  str
 9   Price            10682 non-null  int64
 10  mois_depart      10682 non-null  int32
 11  jour_depart      10682 non-null  int32
 12  duree_min        10682 non-null  int64
dtypes: datetime64[us](1), int32(2), int64(2), str(8)
memory usage: 1.1 MB

In [174]:
data_Train["dep_hour"] = data_Train["Dep_Time"].str.split(":").str[0].astype(int)
data_Train["arr_hour"] = data_Train["Arrival_Time"].str.split(":").str[0].astype(int)

In [175]:
def periode_jour(h):
    if h < 6:
        return "nuit"
    elif h < 12:
        return "matin"
    elif h < 18:
        return "apres_midi"
    else:
        return "soir"

data_Train["periode_depart"] = data_Train["dep_hour"].apply(periode_jour)

In [176]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart,duree_min,dep_hour,arr_hour,periode_depart
0,IndiGo,2019-03-24,Banglore,New Delhi,22:20,01:10,2h 50m,non-stop,No info,3897,3,24,170,22,1,soir
1,Air India,2019-05-01,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,5,1,445,5,13,nuit
2,Jet Airways,2019-06-09,Delhi,Cochin,09:25,04:25,19h,2 stops,No info,13882,6,9,1140,9,4,matin
3,IndiGo,2019-05-12,Kolkata,Banglore,18:05,23:30,5h 25m,1 stop,No info,6218,5,12,325,18,23,soir
4,IndiGo,2019-03-01,Banglore,New Delhi,16:50,21:35,4h 45m,1 stop,No info,13302,3,1,285,16,21,apres_midi

In [177]:
data_Train["Additional_Info"].value_counts()

Additional_Info
No info                         8344
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [178]:
data_Train["Additional_Info"] = (
    data_Train["Additional_Info"]
    .str.lower()
    .str.strip()
)

In [179]:
data_Train["Additional_Info"].value_counts()

Additional_Info
no info                         8347
in-flight meal not included     1982
no check-in baggage included     320
1 long layover                    19
change airports                    7
business class                     4
1 short layover                    1
red-eye flight                     1
2 long layover                     1
Name: count, dtype: int64

In [180]:
data_Train["Source"] = (
    data_Train["Source"]
    .str.lower()
    .str.strip()
)

In [181]:
data_Train["Destination"] = (
    data_Train["Destination"]
    .str.lower()
    .str.strip()
)

In [182]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart,duree_min,dep_hour,arr_hour,periode_depart
0,IndiGo,2019-03-24,banglore,new delhi,22:20,01:10,2h 50m,non-stop,no info,3897,3,24,170,22,1,soir
1,Air India,2019-05-01,kolkata,banglore,05:50,13:15,7h 25m,2 stops,no info,7662,5,1,445,5,13,nuit
2,Jet Airways,2019-06-09,delhi,cochin,09:25,04:25,19h,2 stops,no info,13882,6,9,1140,9,4,matin
3,IndiGo,2019-05-12,kolkata,banglore,18:05,23:30,5h 25m,1 stop,no info,6218,5,12,325,18,23,soir
4,IndiGo,2019-03-01,banglore,new delhi,16:50,21:35,4h 45m,1 stop,no info,13302,3,1,285,16,21,apres_midi

In [184]:
data_Train["Total_Stops"].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [185]:
data_Train["Total_Stops"] = data_Train["Total_Stops"].replace({
    "non-stop": 0,
    "1 stop": 1,
    "2 stops": 2,
    "3 stops": 3,
    "4 stops": 4
})

In [186]:
data_Train.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Date_of_Journey  10682 non-null  datetime64[us]
 2   Source           10682 non-null  str
 3   Destination      10682 non-null  str
 4   Dep_Time         10682 non-null  str
 5   Arrival_Time     10682 non-null  str
 6   Duration         10682 non-null  str
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  str
 9   Price            10682 non-null  int64
 10  mois_depart      10682 non-null  int32
 11  jour_depart      10682 non-null  int32
 12  duree_min        10682 non-null  int64
 13  dep_hour         10682 non-null  int64
 14  arr_hour         10682 non-null  int64
 15  periode_depart   10682 non-null  str
dtypes: datetime64[us](1), int32(2), int64(4), object(1), str(8)
memory usage: 1.3+ MB

In [187]:
data_Train.head()

,Airline,Date_of_Journey,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,mois_depart,jour_depart,duree_min,dep_hour,arr_hour,periode_depart
0,IndiGo,2019-03-24,banglore,new delhi,22:20,01:10,2h 50m,0,no info,3897,3,24,170,22,1,soir
1,Air India,2019-05-01,kolkata,banglore,05:50,13:15,7h 25m,2,no info,7662,5,1,445,5,13,nuit
2,Jet Airways,2019-06-09,delhi,cochin,09:25,04:25,19h,2,no info,13882,6,9,1140,9,4,matin
3,IndiGo,2019-05-12,kolkata,banglore,18:05,23:30,5h 25m,1,no info,6218,5,12,325,18,23,soir
4,IndiGo,2019-03-01,banglore,new delhi,16:50,21:35,4h 45m,1,no info,13302,3,1,285,16,21,apres_midi

In [188]:
data_Train["Total_Stops"] = data_Train["Total_Stops"].astype(int)